name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.405'

      - name: Ensure wwwroot folder exists in API project
        run: |
          if [ ! -d "KaziChapChap.API/wwwroot" ]; then
            echo "wwwroot not found, creating..."
            mkdir -p KaziChapChap.API/wwwroot
            touch KaziChapChap.API/wwwroot/.gitkeep
          else
            echo "wwwroot exists."
          fi

      - name: Restore dependencies
        run: dotnet restore KaziChapChap.API.sln

      - name: Build solution
        run: dotnet build --no-restore KaziChapChap.API.sln

      - name: Run Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --blame KaziChapChap.API.sln
